const request = require('supertest');

process.env.NODE_ENV = 'test';

const app = require('../../src/app');
const { connectDatabases, closeDatabases, sequelize } = require('../../src/config/database');
const User = require('../../src/models/User');
const Car = require('../../src/models/Car');

describe('Hybrid Vehicles API integration tests', () => {
  const userPayload = {
    name: 'Integration Test User',
    email: 'integration.user@example.com',
    password: '123456'
  };

  const carPayload = {
    brand: 'Toyota',
    model: 'Corolla',
    year: 2024,
    color: 'White',
    price: 145000
  };

  beforeAll(async () => {
    await connectDatabases();
    await sequelize.sync();
  });

  beforeEach(async () => {
    await User.unscoped().destroy({
      where: {},
      truncate: true,
      cascade: true,
      restartIdentity: true
    });

    await Car.deleteMany({});
  });

  afterAll(async () => {
    await User.unscoped().destroy({
      where: {},
      truncate: true,
      cascade: true,
      restartIdentity: true
    });

    await Car.deleteMany({});
    await closeDatabases();
  });

  describe('Users and auth routes', () => {
    it('registers a user, returns sanitized user data and a JWT token', async () => {
      const response = await request(app)
        .post('/api/auth/register')
        .send(userPayload)
        .expect(201);

      expect(response.body).toHaveProperty('token');
      expect(response.body.user).toMatchObject({
        id: 1,
        name: userPayload.name,
        email: userPayload.email
      });
      expect(response.body.user).not.toHaveProperty('password');
    });

    it('logs in with valid credentials and returns a JWT token', async () => {
      await request(app).post('/api/auth/register').send(userPayload).expect(201);

      const response = await request(app)
        .post('/api/auth/login')
        .send({
          email: userPayload.email,
          password: userPayload.password
        })
        .expect(200);

      expect(response.body).toHaveProperty('token');
      expect(response.body.user.email).toBe(userPayload.email);
      expect(response.body.user).not.toHaveProperty('password');
    });

    it('lists users without exposing passwords', async () => {
      await request(app).post('/api/auth/register').send(userPayload).expect(201);

      const response = await request(app).get('/api/users').expect(200);

      expect(response.body).toHaveLength(1);
      expect(response.body[0]).toMatchObject({
        name: userPayload.name,
        email: userPayload.email
      });
      expect(response.body[0]).not.toHaveProperty('password');
    });

    it('updates and deletes a user', async () => {
      const registerResponse = await request(app)
        .post('/api/auth/register')
        .send(userPayload)
        .expect(201);

      const userId = registerResponse.body.user.id;

      const updateResponse = await request(app)
        .put(`/api/users/${userId}`)
        .send({ name: 'Updated Integration User' })
        .expect(200);

      expect(updateResponse.body.name).toBe('Updated Integration User');

      await request(app).delete(`/api/users/${userId}`).expect(204);
      await request(app).get(`/api/users/${userId}`).expect(404);
    });
  });

  describe('Cars routes', () => {
    it('rejects protected car creation without a JWT token', async () => {
      const response = await request(app)
        .post('/api/cars')
        .send(carPayload)
        .expect(401);

      expect(response.body.error).toBe('JWT token is missing.');
    });

    it('creates a car with a JWT token generated by login', async () => {
      await request(app).post('/api/auth/register').send(userPayload).expect(201);

      const loginResponse = await request(app)
        .post('/api/auth/login')
        .send({
          email: userPayload.email,
          password: userPayload.password
        })
        .expect(200);

      const token = loginResponse.body.token;

      const createResponse = await request(app)
        .post('/api/cars')
        .set('Authorization', `Bearer ${token}`)
        .send(carPayload)
        .expect(201);

      expect(createResponse.body).toMatchObject(carPayload);
      expect(createResponse.body).toHaveProperty('id');

      const listResponse = await request(app).get('/api/cars').expect(200);

      expect(listResponse.body).toHaveLength(1);
      expect(listResponse.body[0]).toMatchObject(carPayload);
    });

    it('reads, updates and deletes a car with a JWT token', async () => {
      const registerResponse = await request(app)
        .post('/api/auth/register')
        .send(userPayload)
        .expect(201);

      const token = registerResponse.body.token;

      const createResponse = await request(app)
        .post('/api/cars')
        .set('Authorization', `Bearer ${token}`)
        .send(carPayload)
        .expect(201);

      const carId = createResponse.body.id;

      const showResponse = await request(app).get(`/api/cars/${carId}`).expect(200);
      expect(showResponse.body.model).toBe(carPayload.model);

      const updateResponse = await request(app)
        .put(`/api/cars/${carId}`)
        .set('Authorization', `Bearer ${token}`)
        .send({ color: 'Black', price: 150000 })
        .expect(200);

      expect(updateResponse.body.color).toBe('Black');
      expect(updateResponse.body.price).toBe(150000);

      await request(app)
        .delete(`/api/cars/${carId}`)
        .set('Authorization', `Bearer ${token}`)
        .expect(204);

      await request(app).get(`/api/cars/${carId}`).expect(404);
    });
  });
});
